# Generated by Django 5.2.11 on 2026-02-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('OTP_REQUEST', 'OTP Request'), ('LOGIN_SUCCESS', 'Login Success'), ('TASK_CREATE', 'Task Create'), ('TASK_UPDATE', 'Task Update'), ('TASK_DELETE', 'Task Delete')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
